<table>
    <tr>
        <td><tr>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
    </tr>
    <tr>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td></td>

        <td><tr>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
    </tr>
    <tr>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
        <td>dfsf</td>
        </td>
    </tr>
    <table>
        <tr>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
        </tr>
        <tr>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
        </tr>
        <tr>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
            <td>dfsf</td>
        </tr>
    </table>
</table>
